// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpAG4mC4WrRQCPLLJLHgpt32hs5Uq3Elg',
    appId: '1:562176053190:web:4f7c51e88c1c64258a6cc7',
    messagingSenderId: '562176053190',
    projectId: 'fir-project-91c01',
    authDomain: 'fir-project-91c01.firebaseapp.com',
    storageBucket: 'fir-project-91c01.appspot.com',
    measurementId: 'G-M3N08GPLR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC48fDi0lrWL0H5cEn0kHo-GYiabNIeJkE',
    appId: '1:562176053190:android:780ad368020f676f8a6cc7',
    messagingSenderId: '562176053190',
    projectId: 'fir-project-91c01',
    storageBucket: 'fir-project-91c01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR-vCIrOsf707xqkE-YKL8eufzBWKHyB0',
    appId: '1:562176053190:ios:9bace92ff649cda28a6cc7',
    messagingSenderId: '562176053190',
    projectId: 'fir-project-91c01',
    storageBucket: 'fir-project-91c01.appspot.com',
    iosClientId: '562176053190-g1gnjje4ccqsrjlcplf6j3ji7kc9ef56.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );
}
